# Generated by Django 6.0.6 on 2026-06-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
