# Generated by Django 6.0.6 on 2026-07-07 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_report"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="popular_items",
            new_name="popular_dishes",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=36, unique=True
            ),
        ),
    ]
